services:
  api:
    build: .
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - tmp/
            - .git/
            - logs/

  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"
    env_file:
      - .env
    volumes:
      - ./alloy/config.remote.alloy:/etc/alloy/config.alloy
      - ./logs:/logs
    command: run /etc/alloy/config.alloy
